ENT.Type = "anim"
ENT.Base = "base_anim"
ENT.AutomaticFrameAdvance = true
ENT.Model = "models/zerochain/props_pumpkinnight/zpn_partypopper_projectile.mdl"
ENT.Spawnable = false
ENT.AdminSpawnable = false
ENT.PrintName = "Partypopper - Projectile"
ENT.Category = "Zeros PumpkinNight"
ENT.RenderGroup = RENDERGROUP_BOTH
