player_manager.AddValidModel( "SenEgt Bodyguard2", "models/sentry/sentryeightmob/mafia/sentrybusi3male2pm.mdl" )
player_manager.AddValidModel( "SenEgt Bodyguard4", "models/sentry/sentryeightmob/mafia/sentrybusi3male4pm.mdl" )
player_manager.AddValidModel( "SenEgt Bodyguard6", "models/sentry/sentryeightmob/mafia/sentrybusi3male6pm.mdl" )
player_manager.AddValidModel( "SenEgt Bodyguard7", "models/sentry/sentryeightmob/mafia/sentrybusi3male7pm.mdl" )
player_manager.AddValidModel( "SenEgt Bodyguard8", "models/sentry/sentryeightmob/mafia/sentrybusi3male8pm.mdl" )
player_manager.AddValidModel( "SenEgt Bodyguard9", "models/sentry/sentryeightmob/mafia/sentrybusi3male9pm.mdl" )
player_manager.AddValidModel( "SenEgt Assassin2", "models/sentry/sentryeightmob/mafia/sentryprosmale2pm.mdl" )
player_manager.AddValidModel( "SenEgt Assassin4", "models/sentry/sentryeightmob/mafia/sentryprosmale4pm.mdl" )
player_manager.AddValidModel( "SenEgt Assassin6", "models/sentry/sentryeightmob/mafia/sentryprosmale6pm.mdl" )
player_manager.AddValidModel( "SenEgt Assassin7", "models/sentry/sentryeightmob/mafia/sentryprosmale7pm.mdl" )
player_manager.AddValidModel( "SenEgt Assassin8", "models/sentry/sentryeightmob/mafia/sentryprosmale8pm.mdl" )
player_manager.AddValidModel( "SenEgt Assassin9", "models/sentry/sentryeightmob/mafia/sentryprosmale9pm.mdl" )
player_manager.AddValidModel( "SenEgt Mafia1", "models/sentry/sentryeightmob/mafia/sentrykorlitmale1pm.mdl" )
player_manager.AddValidModel( "SenEgt Mafia2", "models/sentry/sentryeightmob/mafia/sentrykorlitmale2pm.mdl" )
player_manager.AddValidModel( "SenEgt Mafia3", "models/sentry/sentryeightmob/mafia/sentrykorlitmale3pm.mdl" )
player_manager.AddValidModel( "SenEgt Mafia4", "models/sentry/sentryeightmob/mafia/sentrykorlitmale4pm.mdl" )
player_manager.AddValidModel( "SenEgt Mafia6", "models/sentry/sentryeightmob/mafia/sentrykorlitmale6pm.mdl" )
player_manager.AddValidModel( "SenEgt Mafia7", "models/sentry/sentryeightmob/mafia/sentrykorlitmale7pm.mdl" )
player_manager.AddValidModel( "SenEgt Mafia8", "models/sentry/sentryeightmob/mafia/sentrykorlitmale8pm.mdl" )
player_manager.AddValidModel( "SenEgt Mafia9", "models/sentry/sentryeightmob/mafia/sentrykorlitmale9pm.mdl" )
player_manager.AddValidModel( "SenEgt Goon2", "models/sentry/sentryeightmob/mafia/sentrychibossmale2pm.mdl" )
player_manager.AddValidModel( "SenEgt Goon4", "models/sentry/sentryeightmob/mafia/sentrychibossmale4pm.mdl" )
player_manager.AddValidModel( "SenEgt Goon6", "models/sentry/sentryeightmob/mafia/sentrychibossmale6pm.mdl" )
player_manager.AddValidModel( "SenEgt Goon7", "models/sentry/sentryeightmob/mafia/sentrychibossmale7pm.mdl" )
player_manager.AddValidModel( "SenEgt Goon8", "models/sentry/sentryeightmob/mafia/sentrychibossmale8pm.mdl" )
player_manager.AddValidModel( "SenEgt Goon9", "models/sentry/sentryeightmob/mafia/sentrychibossmale9pm.mdl" )
player_manager.AddValidModel( "SenEgt Boss2", "models/sentry/sentryeightmob/mafia/sentrykorbossmale2pm.mdl" )
player_manager.AddValidModel( "SenEgt Boss4", "models/sentry/sentryeightmob/mafia/sentrykorbossmale4pm.mdl" )
player_manager.AddValidModel( "SenEgt Boss5", "models/sentry/sentryeightmob/mafia/sentrykorbossmale5pm.mdl" )
player_manager.AddValidModel( "SenEgt Boss6", "models/sentry/sentryeightmob/mafia/sentrykorbossmale6pm.mdl" )
player_manager.AddValidModel( "SenEgt Boss7", "models/sentry/sentryeightmob/mafia/sentrykorbossmale7pm.mdl" )
player_manager.AddValidModel( "SenEgt Boss8", "models/sentry/sentryeightmob/mafia/sentrykorbossmale8pm.mdl" )
player_manager.AddValidModel( "SenEgt Boss9", "models/sentry/sentryeightmob/mafia/sentrykorbossmale9pm.mdl" )
player_manager.AddValidModel( "SenEgt Suit1", "models/sentry/sentryeightmob/misc/sentryhighsecmale1pm.mdl" )
player_manager.AddValidModel( "SenEgt Suit2", "models/sentry/sentryeightmob/misc/sentryhighsecmale2pm.mdl" )
player_manager.AddValidModel( "SenEgt Suit3", "models/sentry/sentryeightmob/misc/sentryhighsecmale3pm.mdl" )
player_manager.AddValidModel( "SenEgt Suit4", "models/sentry/sentryeightmob/misc/sentryhighsecmale4pm.mdl" )
player_manager.AddValidModel( "SenEgt Suit6", "models/sentry/sentryeightmob/misc/sentryhighsecmale6pm.mdl" )
player_manager.AddValidModel( "SenEgt Suit7", "models/sentry/sentryeightmob/misc/sentryhighsecmale7pm.mdl" )
player_manager.AddValidModel( "SenEgt Suit8", "models/sentry/sentryeightmob/misc/sentryhighsecmale8pm.mdl" )
player_manager.AddValidModel( "SenEgt Suit9", "models/sentry/sentryeightmob/misc/sentryhighsecmale9pm.mdl" )
player_manager.AddValidModel( "SenEgt Triad", "models/sentry/sentryeightmob/misc/sentrybusi2male5pm.mdl" )
player_manager.AddValidModel( "SenEgt CartelSuit", "models/sentry/sentryeightmob/misc/sentrymexgangmale4pm.mdl" )
player_manager.AddValidModel( "SenEgt CartelGoon", "models/sentry/sentryeightmob/misc/sentrychigoon1male4pm.mdl" )
player_manager.AddValidModel( "SenEgt TropicalGoon1", "models/sentry/sentryeightmob/misc/sentrysoucent2male1pm.mdl" )
player_manager.AddValidModel( "SenEgt TropicalGoon3", "models/sentry/sentryeightmob/misc/sentrysoucent2male3pm.mdl" )

local nextName
local tbNPCs = {}

local function AddNPC(category, name, class, model, keyvalues, weapons, spawnflags)
		list.Set("NPC",name,{Name = name,Class = class,Model = model,Category = category,KeyValues = keyvalues,Weapons = weapons, SpawnFlags = spawnflags})
		tbNPCs[name] = model
end

AddNPC("GTA V", "SenEgt Cartel Goon", "npc_citizen", "models/sentry/sentryeightmob/misc/sentrychigoon1male4g.mdl", {citizentype = CT_UNIQUE, SquadName = "rebels"}, {"weapon_pistol","weapon_smg1"})
AddNPC("GTA V", "SenEgt Asian Suit", "npc_citizen", "models/sentry/sentryeightmob/misc/sentrybusi2male5g.mdl", {citizentype = CT_UNIQUE, SquadName = "rebels"}, {"weapon_pistol","weapon_smg1"})
