ENT.Type = "anim"
ENT.Base = "base_anim"
ENT.AutomaticFrameAdvance = true
ENT.Model = "models/zerochain/props_pumpkinnight/zpn_pumpkin01.mdl"
ENT.Spawnable = false
ENT.AdminSpawnable = false
ENT.PrintName = "Firearea"
ENT.Category = "Zeros PumpkinNight"
ENT.RenderGroup = RENDERGROUP_OPAQUE
